config/routes.rb
Rails.application.routes.draw do
  # post 'sessions/login', to: 'sessions#login', as: 'login'
  # get 'sessions/login', to: 'sessions#new', as: 'login_form'
  # delete 'sessions/destroy', to: 'sessions#destroy', as: 'logout'

  get "/auth/:provider/callback", to: "sessions#create", as: 'auth_callback'
  delete "/logout", to: "sessions#destroy", as: "logout"

  root "books#index"

  resources :books

  #get '/authors/:author_id/books', to: 'books#index'

  resources :authors do
    resources :books, only: [:index, :new]
  end

  # get '/authors/:id', to: 'authors#show', as: 'author'

  # get '/books', to: 'books#index', as: 'books'
  #
  # get '/books/new', to: 'books#new', as: 'new_book'
  # post '/books', to: 'books#create'
  #
  # get '/books/:id/edit', to: 'books#edit', as: 'edit_book'
  #
  # get '/books/:id', to: 'books#show', as: 'book'
  #
  # patch '/books/:id/complete', to: 'books#mark_complete', as: 'mark_complete'
  #
  # patch '/books/:id', to: 'books#update', as: 'update_book'
  # put '/books/:id', to: 'books#update'
  #
  # delete '/books/:id', to: 'books#destroy'

  #delete '/books/:id', to: 'books#destroy'

  # get '/books/show'
  # get '/books/whozeewhatsit'
  # get '/authors', to: 'authors#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/author.rb
class Author < ApplicationRecord
  has_many :books
  has_many :genres, through: :books

  def self.author_list
    return Author.all.map do |author|
      [author.name , author.id]
    end
  end

  def first_published
    books_with_year = self.books.where.not(date_published: nil)
    first_book = books_with_year.order(date_published: :asc).first
    if first_book != nil
      return first_book.date_published
    else
      return nil
    end
  end

  def most_recent_book
    books_with_year = self.books.where.not(date_published: nil)
    latest_book = books_with_year.order(date_published: :asc).last
    if latest_book != nil
      return latest_book.title
    else
      return nil
    end
  end
end

app/models/book.rb
class Book < ApplicationRecord
  belongs_to :author
  has_and_belongs_to_many :genres

  validates :title, presence: true, length: { in: 5..100 }
  validates :title, uniqueness: true
end

app/models/genre.rb
class Genre < ApplicationRecord
  has_and_belongs_to_many :books
end

app/models/user.rb
class User < ApplicationRecord
  # Turn the auth hash into an instance
  # of class User
  def self.build_from_github(auth_hash)
   user = User.new
   user.uid = auth_hash[:uid]
   user.provider = 'github'
   user.name = auth_hash['info']['name']
   user.email = auth_hash['info']['email']

   # Note that the user has not been saved
   return user
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :set_cache_headers
  before_action :find_user


    private

    def find_user
       @current_user ||= User.find(session[:user_id]) if session[:user_id]
     end

     def require_login
       if find_user.nil?
         flash[:error] = "You must be logged in to view this section"
         redirect_to root_path
       end
     end

    def set_cache_headers
      response.headers["Cache-Control"] = "no-cache, no-store"
      response.headers["Pragma"] = "no-cache"
      response.headers["Expires"] = "Fri, 01 Jan 1990 00:00:00 GMT"
    end
end

app/controllers/authors_controller.rb
class AuthorsController < ApplicationController
  def index
    @authors = Author.order(:name)
  end
  
  def show
    id = params[:id].to_i
    @author = Author.find_by(id: id)


    if @author.nil?
     render :notfound, status: :not_found
    end
  end
end

app/controllers/books_controller.rb
# BOOKS = [
#   { id: 1, title: "Hidden Figures", author: "Margot Lee Shetterly", description: "Inspiring"},
#   { id: 2, title: "Practical Object-Oriented Design in Ruby", author: "Sandi Metz", description: "Best Ruby book"},
#   { id: 47, title: "Kindred", author: "Octavia E. Butler", description: "Scary"}
# ]

class BooksController < ApplicationController
  before_action :find_book, only: [:show, :edit, :update, :destroy]
  before_action :require_login, except: [:index, :show]

  def index
    if params[:author_id]
      author_id = params[:author_id]
      @books = Author.find_by(id: author_id).books.order(:title)
    else
      @books = Book.all.order(:title)
    end
  end

  def show;  end


  def new
    @book = Book.new
    if params[:author_id]
      @author_id = params[:author_id].to_i
      author = Author.find_by(id: @author_id)
      if author.nil?
        flash.now[:warning] = "That author doesn't exit"
      end
      @book.author_id = @author_id

    end
  end

  def edit; end



  def destroy
    unless @book.nil?
      @book.destroy
      flash[:success] = "#{@book.title} deleted"
      redirect_to root_path
    end
  end

  def create
    @book = Book.new(book_params)
    if @book.save # save returns true if the database insert succeeds
      flash[:success] = 'Book Created!'

      redirect_to root_path # go to the index so we can see the book in the list
    else # save failed :(
      flash.now[:danger] = 'Book not created!'

      render :new, status: :bad_request # show the new book form view again
    end
  end

  def update
    if @book && @book.update(book_params)
      redirect_to book_path(@book.id)
    elsif @book
      render :edit, status: :bad_request
    end
  end

  private

  def find_book
    @book = Book.find_by(id: params[:id].to_i)

    if @book.nil?
      flash.now[:danger] = "Cannot find the book #{params[:id]}"
      render :notfound, status: :not_found
    end
  end

  def book_params
    return params.require(:book).permit(:title, :author_id, :description)
  end







end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  # def login
  #   author = Author.find_by(name: params[:author][:name])
  #
  #   if author.nil?
  #     # Create a new author
  #     author = Author.create(name: params[:author][:name])
  #   end
  #
  #   session[:user_id] = author.id
  #   flash[:success] = "#{author.name} Successfully logged in!"
  #   redirect_to root_path
  # end
  #
  # def new
  #   @author = Author.new
  # end
  #
  # def destroy
  #   session[:user_id] = nil
  #   flash[:success] = 'Successfully logged out'
  #   redirect_back fallback_location: root_path
  # end

  def create
    auth_hash = request.env['omniauth.auth']
    user = User.find_by(uid: auth_hash[:uid], provider: 'github')
    if user
      # User was found in the database
      flash[:success] = "Logged in as returning user #{user.name}"
    else
      # User doesn't match anything in the DB
      # Attempt to create a new user
      user = User.build_from_github(auth_hash)

      if user.save
        flash[:success] = "Logged in as new user #{user.name}"

      else
        # Couldn't save the user for some reason. If we
        # hit this it probably means there's a bug with the
        # way we've configured GitHub. Our strategy will
        # be to display error messages to make future
        # debugging easier.
        flash[:error] = "Could not create new user account: #{user.errors.messages}"
        redirect_to root_path
        return
      end
    end

    session[:user_id] = user.id
    redirect_to root_path
  end

  def destroy
    session[:user_id] = nil
    flash[:success] = "Successfully logged out!"

    redirect_to root_path
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def readable_date(date)
    ("<span class='date'>" + date.strftime("%A, %b %d") + "</span>").html_safe
  end
  def random_image(width, height)
    number = rand(3)
    url = ""
    case number
    when 0
      url = "https://picsum.photos/"
    when 1
      url = "http://www.placecage.com/"
    when 2
      url = "http://placekitten.com/"
    end
    ["<img src='", url, width,"/" ,height, "' alt='random image'>"].join.html_safe
  end
end

app/helpers/authors_helper.rb
module AuthorsHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/views/authors/index.html.erb
<h2>Ada Books Authors</h2>
<ul>
  <% @authors.each do |author| %>
    <li><%= link_to author.name, author_path(author.id) %>
  <% end %>
</ul>

app/views/authors/show.html.erb
<% if @author.nil? %>
  <h1> 404 Not found</h1>
<% else %>
  <h1><%=@author.name %></h1>
  <h2>Genres</h2>
  <ul>
    <% @author.genres.each do |genre| %>
      <li><%= genre.name %></li>
    <% end %>
  </ul>
  <p><%= @author.first_published %> </p>
  <p><%= link_to "Books by #{@author.name}", author_books_path(@author.id) %>




  <%= link_to "Add a book", new_author_book_path(@author.id) %>
<% end %>

app/views/books/_form.html.erb
<h1> <%= action_name %> </h1>

<%= render partial: "layouts/form_errors", locals: { model: @book } %>

<%= form_with model: @book, class: "book-form"  do |f|%>
  <p>Please provide the following information to save your book to our database:</p>

  <%= f.label :title %>
  <%= f.text_field :title %>

  <%= f.label :author_id, "Author" %>
  <%= f.select :author_id, Author.author_list %>
  <section class="description-section">
    <%= f.label :description %>
    <%= f.text_area :description %>
  </section>
  <%#= f.select :author_id, [ ['Bob', 1], ['Ada', 2], ['JK', 42]  ] %>

  <%# f.text_field :author %>

  <%# f.hidden :creator, value: 'Divya' %>

  <%= f.submit button_title, class: "book-button btn btn-primary" %>
<% end %>

app/views/books/create.html.erb
<%= render partial: "form",
      locals: { action_name: 'Create a book',
                 button_title: 'Create' } %>

app/views/books/destroy.html.erb
<%= "You have deleted #{@deleted_book.title}" %>

app/views/books/edit.html.erb
<%= render partial: "form",
      locals: { action_name: 'Edit a book',
                 button_title: 'Edit' } %>

app/views/books/index.html.erb
<!-- <%# name = 'bob' %>
<ul>
<%# 5.times do |i| %>
  <li> <%#= "#{name} is number #{i}".upcase %>  </li>
<%# end %>
</ul> -->


<h1>These are the books!</h1>
<% @books.each do |book| %>
  <h2><%= link_to "This IS: #{book.title}", book_path(book.id) %>
  </h2>
</a>
  <p> by <%= book.author.name %></p>
  <%= link_to "Delete", book_path(book.id), method: :delete %>
<% end %>

app/views/books/new.html.erb
<%= render partial: "form",
      locals: { action_name: 'Create a book',
                 button_title: 'Create' } %>

app/views/books/notfound.html.erb
<h1>Not Found 404 </h1>

app/views/books/show.html.erb
<% if @book.nil? %>
  <h1> 404 Not found</h1>
<% else %>
  <h1><%=@book.title %></h1>
  <%= readable_date(@book.created_at) %>
  <%= random_image(300, 400) %>
  <h3> by <%= link_to "#{@book.author.name}", author_path(@book.author.id) %></h3>
  <p><%= @book.description %> </p>
  <%= link_to "Edit", edit_book_path(@book.id) %>
  <div></div>
  <%= link_to "Delete #{@book.title}", book_path(@book.id), method: :delete %>
<% end %>

app/views/layouts/_form_errors.html.erb
<% if model.errors.any? %>
  <ul class="errors">
    <% model.errors.messages.each do |column, problem_list| %>
      <% problem_list.each do |problem| %>
        <li>
          <strong>
            <%= column.capitalize %>
          </strong>
          <%= problem %>
        </li>
      <% end %>
    <% end %>
  </ul>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>AdaBooksNodes</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <header>
      <section class="flash">
        <% flash.each do |name, message| %>
          <% if message.class == Array %>
          <div class="alert-warning">
            <% message.each do |msg| %>
                <p><strong><%= "#{name}:" %></strong><%= " #{msg}" %></p>
            <% end %>
          </div>
          <% else %>
            <div class="alert-<%= name %>">
                <%= message %>
            </div>
          <% end %>
        <% end %>

        <% if @current_user %>
          <h2>Welcome <%= @current_user.name %> </h2>
        <% end %>
      </section>
      <h1>Welcome to Ada Books!</h1>
      <nav>
        <ul>
          <li>
            <%= link_to  "Home", "/", id: "home-link" %>
          </li>
         <li>
           <%= link_to "Books Index", books_path %>
         </li>
         <li>
           <%= link_to "Authors Index", authors_path %>
         <li>
           <a href="<%= new_book_path%>">
             Add a book
           </a>
         </li>
         <li>
           <% if session[:user_id] %>
             <%= link_to "Log out", logout_path, method: "delete"   %>
           <% else %>
             <%= link_to "Login with Github", "/auth/github" %>
           <% end %>
          </li>
        </ul>
      </nav>
    </header>
    <main>
      <%= yield %>
    </main>
  </body>
</html>